# ec2 specific settings

host_ioc_zpool_devices: 'nvd1' # device settings used when creating the pool
host_srv_zpool_devices: 'nvd1' # device settings used when creating the pool

host_sshd_user: 'ec2-user'
sshd_user: 'ec2-user'
