- name: Install ssmtp for easy mail forwarding
  pkgng:
    name: 'ssmtp'
    state: present
  register: pkg_result
  until: pkg_result is succeeded

- name: Copy ssmtp.conf into place
  template:
    backup: '{{ host_backup_old_files }}'
    src: 'ssmtp.conf.j2'
    dest: '/usr/local/etc/ssmtp/ssmtp.conf'

- name: Copy mailer configuration into place
  template:
    backup: '{{ host_backup_old_files }}'
    src: 'mailer.conf.j2'
    dest: '/etc/mail/mailer.conf'
