- name: Configure syslog
  lineinfile:
    backup: '{{ host_backup_old_files }}'
    dest: '/etc/syslog.conf'
    state: present
    line: '*.*      @{{ host_syslogd_server }}'
    insertafter: '^#\s+Consult the syslog.conf'
  notify:
    - Reload host syslogd

- name: Enable remote syslog logging
  lineinfile:
    backup: '{{ host_backup_old_files }}'
    dest: '/etc/rc.conf'
    regexp: 'syslogd_flags='
    line: 'syslogd_flags="-c -s"'
  notify:
    - Reload host syslogd
